stages:
  - deploy

deploy_production:
  stage: deploy
  when: manual
  tags:
    - shell
  script:
    - echo "Deploying to server"
    - docker-compose up -d
    - echo "Deployed"
  only:
    - master