version: "3.8"
networks:
  traefik_net:
    external: true
services:
  cli2-light:
    build: .
    ports:
      - "8080:80"
    container_name: cli2-light
    networks:
      - traefik_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cli2-light.entrypoints=https"
      - "traefik.http.routers.cli2-light.rule=Host(`cli.icc.spb.ru`)"
      - "traefik.http.routers.cli2-light.tls=true"
      - "traefik.http.routers.cli2-light.tls.certresolver=letsEncrypt"
      - "traefik.http.services.cli2-light-service.loadbalancer.server.port=80"