import React from 'react'

const BigLorem = () => {
  return(
    <React.Fragment>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias assumenda blanditiis debitis dicta dignissimos dolore dolores eius esse ex, fugiat fugit illum incidunt iure labore magnam minus natus necessitatibus, odio omnis provident quia saepe sint temporibus totam ullam vero voluptatibus? A accusamus, consectetur error in molestiae nobis reprehenderit. Accusantium aliquid architecto culpa cumque deserunt dolorum ea, esse facilis impedit ipsa labore magni maiores modi natus necessitatibus nobis omnis pariatur perspiciatis quasi qui ratione sapiente temporibus. Accusantium aliquid, autem culpa delectus ea et harum non numquam pariatur quasi quo quos, rem repellat sequi sint unde vitae! Aliquid aperiam asperiores atque, ex expedita facilis harum laudantium neque nesciunt non odit officiis quod velit! Aliquam eius enim error, iure sint unde. Aliquid asperiores aut corporis deserunt dolore ea error eum explicabo hic illo inventore ipsa ipsam iste maxime modi, molestias nesciunt nulla officiis perspiciatis placeat possimus quia quod repellendus rerum saepe, sit sunt suscipit temporibus, tenetur vel veniam veritatis voluptas voluptatem. Blanditiis, commodi consequatur corporis est eveniet exercitationem harum hic labore perspiciatis sint. Laudantium officia placeat saepe! A animi assumenda at error impedit incidunt ipsam maiores mollitia natus, nobis numquam, odit omnis, praesentium quisquam soluta sunt ut vel! Distinctio nemo quia quod vero?
      </p>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias assumenda blanditiis debitis dicta dignissimos dolore dolores eius esse ex, fugiat fugit illum incidunt iure labore magnam minus natus necessitatibus, odio omnis provident quia saepe sint temporibus totam ullam vero voluptatibus? A accusamus, consectetur error in molestiae nobis reprehenderit. Accusantium aliquid architecto culpa cumque deserunt dolorum ea, esse facilis impedit ipsa labore magni maiores modi natus necessitatibus nobis omnis pariatur perspiciatis quasi qui ratione sapiente temporibus. Accusantium aliquid, autem culpa delectus ea et harum non numquam pariatur quasi quo quos, rem repellat sequi sint unde vitae! Aliquid aperiam asperiores atque, ex expedita facilis harum laudantium neque nesciunt non odit officiis quod velit! Aliquam eius enim error, iure sint unde. Aliquid asperiores aut corporis deserunt dolore ea error eum explicabo hic illo inventore ipsa ipsam iste maxime modi, molestias nesciunt nulla officiis perspiciatis placeat possimus quia quod repellendus rerum saepe, sit sunt suscipit temporibus, tenetur vel veniam veritatis voluptas voluptatem. Blanditiis, commodi consequatur corporis est eveniet exercitationem harum hic labore perspiciatis sint. Laudantium officia placeat saepe! A animi assumenda at error impedit incidunt ipsam maiores mollitia natus, nobis numquam, odit omnis, praesentium quisquam soluta sunt ut vel! Distinctio nemo quia quod vero?
      </p>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias assumenda blanditiis debitis dicta dignissimos dolore dolores eius esse ex, fugiat fugit illum incidunt iure labore magnam minus natus necessitatibus, odio omnis provident quia saepe sint temporibus totam ullam vero voluptatibus? A accusamus, consectetur error in molestiae nobis reprehenderit. Accusantium aliquid architecto culpa cumque deserunt dolorum ea, esse facilis impedit ipsa labore magni maiores modi natus necessitatibus nobis omnis pariatur perspiciatis quasi qui ratione sapiente temporibus. Accusantium aliquid, autem culpa delectus ea et harum non numquam pariatur quasi quo quos, rem repellat sequi sint unde vitae! Aliquid aperiam asperiores atque, ex expedita facilis harum laudantium neque nesciunt non odit officiis quod velit! Aliquam eius enim error, iure sint unde. Aliquid asperiores aut corporis deserunt dolore ea error eum explicabo hic illo inventore ipsa ipsam iste maxime modi, molestias nesciunt nulla officiis perspiciatis placeat possimus quia quod repellendus rerum saepe, sit sunt suscipit temporibus, tenetur vel veniam veritatis voluptas voluptatem. Blanditiis, commodi consequatur corporis est eveniet exercitationem harum hic labore perspiciatis sint. Laudantium officia placeat saepe! A animi assumenda at error impedit incidunt ipsam maiores mollitia natus, nobis numquam, odit omnis, praesentium quisquam soluta sunt ut vel! Distinctio nemo quia quod vero?
      </p>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias assumenda blanditiis debitis dicta dignissimos dolore dolores eius esse ex, fugiat fugit illum incidunt iure labore magnam minus natus necessitatibus, odio omnis provident quia saepe sint temporibus totam ullam vero voluptatibus? A accusamus, consectetur error in molestiae nobis reprehenderit. Accusantium aliquid architecto culpa cumque deserunt dolorum ea, esse facilis impedit ipsa labore magni maiores modi natus necessitatibus nobis omnis pariatur perspiciatis quasi qui ratione sapiente temporibus. Accusantium aliquid, autem culpa delectus ea et harum non numquam pariatur quasi quo quos, rem repellat sequi sint unde vitae! Aliquid aperiam asperiores atque, ex expedita facilis harum laudantium neque nesciunt non odit officiis quod velit! Aliquam eius enim error, iure sint unde. Aliquid asperiores aut corporis deserunt dolore ea error eum explicabo hic illo inventore ipsa ipsam iste maxime modi, molestias nesciunt nulla officiis perspiciatis placeat possimus quia quod repellendus rerum saepe, sit sunt suscipit temporibus, tenetur vel veniam veritatis voluptas voluptatem. Blanditiis, commodi consequatur corporis est eveniet exercitationem harum hic labore perspiciatis sint. Laudantium officia placeat saepe! A animi assumenda at error impedit incidunt ipsam maiores mollitia natus, nobis numquam, odit omnis, praesentium quisquam soluta sunt ut vel! Distinctio nemo quia quod vero?
      </p>
    </React.Fragment>
  )
}

export default BigLorem